name: my_puzzle
description: A beautiful puzzle game that allows users to create puzzles from their own images.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  image_picker: ^0.8.7
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 